// Generated by CoffeeScript 1.8.0
(() => {
  Strophe.addNamespace('CAPS', 'http://jabber.org/protocol/caps');
  Strophe.addConnectionPlugin('caps', {
    _c: null,

    init: function(conn) {
      this._c = conn;

      if (!conn.disco) throw new Error('disco plugin required!');

      conn.disco.addFeature(Strophe.NS.CAPS);
      conn.disco.addFeature(Strophe.NS.DISCO_INFO);
    },

    pres: function(attrs) {
      const caps = this.createCapsNode().tree();
      return $pres(attrs).cnode(caps).up();
    },

    createCapsNode: function() {
      let node;
      if (this._c.disco._identities.length > 0)
        node = this._c.disco._identities[0].name || '';
      else
        node = dummyId.name;

      return $build('c', {
        xmlns: Strophe.NS.CAPS,
        hash: 'sha-1',
        node,
        ver: SHA1.b64_sha1(this.ver()),
      });
    },

    ver: function() {
      const identities = Array.from(this._c.disco._identities);
      const features = Array.from(this._c.disco._features).sort();

      propertySort(identities, 'category');
      propertySort(identities, 'type');
      propertySort(identities, 'lang');

      let S = '';
      for (let key in identities) {
        const id = identities[key];
        S += [id.category, id.type, id.lang, id.name].join('/') + '<';
      }

      for (let ns of features)
        S += String(ns) + '<';

      return S;
    }
  });

  const propertySort = (array, property) => {
    return array.sort((a, b) => {
      return (a[property] > b[property]) ? -1 : 1;
    });
  };
})();
